### ISSUE TITLE
Dependency issues on Linux

### ISSUE THREAD

**Issue by AugustT** [GitTFJ/classecol#1]
I'm struggling to get this to install on a linux system. There seems to be a dependency on talgalili/installr which comes from addeR, and installr is Windows only. Does this mean classecol is windows only?

I'm wanting to run this package on a (linux) supercomputer to be able to classify 2 million social media messages in a reasonable amount of time, so would be good to chat anyway about the package.

**Comment by AugustT** [comment]
@GitTFJ

**Comment by GitTFJ** [comment]
Tom, thank you for trying classecol. The package has been tested on a linux os (although not by myself) and I had been told all was working well. I will chase this to confirm they have checked the most recent classecol version which uses addeR, and not the old version which used reticulate. 

If the issue is coming from the talgalili/installr dependency, this will be an easy fix as this dependency is only used to automate the python install. I will develop a more streamlined solution in the coming weeks (and update classecol accordingly) when I can get hold of linux os myself. If your work is urgent, I am happy to chat with you and come up with a temporary fix? This fix could be to call the classecol-python models directly from your linux terminal instead of through the classecol package, which may be preferable for supercomputer reasons.

Contact me on thomas.frederick.johnson(at)outlook.com if you want to arrange a chat

**Comment by AugustT** [comment]
@GitTFJ Still stuck on this one. How are you getting on? To move things along I'm going to start working on a fork that removes the dependency

**Comment by AugustT** [comment]
I have opened an issue on adder for the installer issue

**Comment by GitTFJ** [comment]
I have tackled these dependency issues in the most recent version of addeR [https://github.com/GitTFJ/addeR/issues/1](url)
