### ISSUE TITLE
Issues with Mac OS

### ISSUE THREAD

**Issue by GitTFJ** [GitTFJ/classecol#4]
Some issues have been detected in the automated install of python for Mac OS. A fix is scheduled for January but I am willing to provide manual guidance in the meantime (upon request)

**Comment by Dr-Nathan-Fox** [comment]
Are you able to provide some assistance on linking R to python for macs, 

I have some students trying to do this but we can't figure out how to link the two.

**Comment by GitTFJ** [comment]
There is fault in the current version of the load_classecol() function. This should bypassed by running 

`load_classecol(download_models = T, download_modules = T, link_py = F)`

and then linking python manually by running

`reticulate::use_python(Sys.which("python3"))`

However, Python is no longer maintaining version 3.6.8, and so there are new errors popping up daily, especially using M-chips from Mac. You may be able to run your code problem free by linking python as shown above, but I currently can't on my M1...

Over the christmas break I will be re-writing the package using the new machine learning functionality in R to address these issues, but I am too pressed for time to implement these any sooner. Apologies I can't help more

**Comment by GitTFJ** [comment]
If the python modules are also failing to download, this can be resolved with the following R script (example shows the keras package):

`system("python3 -m pip install keras")`

**Comment by yiluansong** [comment]
Hi @GitTFJ ,

Thank you so much for your tips! I have been able to load python3 on Linux and install some packages. However, I still encountered the following error when running each of the major functions.
Caused by error in py_run_file_impl():
! ModuleNotFoundError: No module named 'sklearn.linear_model.stochastic_gradient'
I have checked the .py files in the source but did not see any usage of sklearn.linear_model.stochastic_gradient. I also tried downgrading my scikit-learn to 0.24.2 but that did not help. Could you provide some suggestions on this?

In addition, classecol::clean does not work for the example with the following error.
Error in nchar(pattern) : invalid multibyte string, element 85

Thank you!

**Comment by GitTFJ** [comment]
Hi @yiluansong ,

This the first time I've heard of an issue with Linux, so thank you for flagging this.

I will be working on the new version of the package this week, and so instead of trying to debug your error, I recommend waiting for the new release, scheduled before January. It promises to be far easier to use and more robust.

Best, Tom

**Comment by yiluansong** [comment]
Thank you so much! All the best for the new release.

**Comment by GitTFJ** [comment]
I've released the new version of the package. It should be much much much simpler to use now as it's all based in R. This has made it slower, but not by a crazy amount. The package still under going system tests. But it should be relatively robust...
